CREATE TABLE PALCO(
    NUMERO NUMBER(3) NOT NULL,
    SETOR VARCHAR2(3),
    CONSTRAINT PK_PALCO PRIMARY KEY (NUMERO)
);

CREATE TABLE COMPETIDOR(
    INSCRICAO NUMBER(3) NOT NULL,
    TIPO VARCHAR2(5) DEFAULT 'SOLO',
    NRO_PONTOS NUMBER(3),
    PALCO NUMBER(3),
    CONSTRAINT CK_TIPO_COMP CHECK(TIPO IN('SOLO', 'GRUPO')),
    CONSTRAINT FK_COMPETIDOR FOREIGN KEY (PALCO) REFERENCES PALCO (NUMERO),
    CONSTRAINT PK_COMPETIDOR PRIMARY KEY (INSCRICAO)
);

CREATE TABLE GRUPO(
    INSCRICAO NUMBER(3) NOT NULL,
    QTD_PESSOAS NUMBER(2),
    CONSTRAINT FK_GRUPO FOREIGN KEY (INSCRICAO) REFERENCES COMPETIDOR (INSCRICAO),
    CONSTRAINT PK_GRUPO PRIMARY KEY (INSCRICAO)
);

CREATE TABLE COSPLAYER(
    CPF NUMBER(14) NOT NULL,
    NOME VARCHAR2(50),
    NOME_PERSONAGEM VARCHAR2(50),
    ORIGEM_PERSONAGEM VARCHAR2(50),
    TELEFONE VARCHAR2(20),
    NRO_VOTOS NUMBER(3),
    ENDERECO VARCHAR2(50),
    GRUPO NUMBER(3),
    CONSTRAINT FK_COSPLAYER FOREIGN KEY (GRUPO) REFERENCES GRUPO (INSCRICAO),
    CONSTRAINT PK_COSPLAYER PRIMARY KEY (CPF)
);

CREATE TABLE VOTANTE(
    CPF NUMBER(14) NOT NULL,
    EMAIL VARCHAR2(40),
    COSPLAYER NUMBER(14) NOT NULL,
    CONSTRAINT FK_VOTANTE FOREIGN KEY (COSPLAYER) REFERENCES COSPLAYER (CPF),
    CONSTRAINT PK_VOTANTE PRIMARY KEY (CPF)
);